name: Experimental Windows Build

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  CARGO_HOME: D:\cargo_short
  GIT_CLONE_PATH: D:\git_clones

jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure short paths
        run: |
          mkdir D:\cargo_short
          mkdir D:\git_clones

      - name: Install Rust (Windows)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true

      - name: Build (Release)
        run: |
          cargo build --release --target x86_64-pc-windows-msvc --no-default-features
          dir target\x86_64-pc-windows-msvc\release\

      - name: Package artifacts
        run: |
          mkdir zed-windows
          copy target\x86_64-pc-windows-msvc\release\zed.exe zed-windows\
          7z a zed-windows-nightly.zip zed-windows\

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zed-windows-nightly
          path: zed-windows-nightly.zip
